//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ButikSite.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ButikSiteEntities : DbContext
    {
        public ButikSiteEntities()
            : base("name=ButikSiteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TblKategoriler> TblKategoriler { get; set; }
        public virtual DbSet<TblMarkalar> TblMarkalar { get; set; }
        public virtual DbSet<TblMüşteriler> TblMüşteriler { get; set; }
        public virtual DbSet<TblÜrünler> TblÜrünler { get; set; }
        public virtual DbSet<TblSatışlar> TblSatışlar { get; set; }
        public virtual DbSet<TblMesajlar> TblMesajlar { get; set; }
        public virtual DbSet<TblYorumlar> TblYorumlar { get; set; }
        public virtual DbSet<TblDuyurular> TblDuyurular { get; set; }
        public virtual DbSet<TblAdmin> TblAdmin { get; set; }
        public virtual DbSet<TblFavoriler> TblFavoriler { get; set; }
        public virtual DbSet<TblSepetim> TblSepetim { get; set; }
    
        public virtual ObjectResult<string> trendler()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("trendler");
        }
    
        public virtual ObjectResult<string> enazalımlımüşteri()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("enazalımlımüşteri");
        }
    
        public virtual ObjectResult<string> enazsatılankategorı()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("enazsatılankategorı");
        }
    
        public virtual ObjectResult<string> enazsatılanMarka()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("enazsatılanMarka");
        }
    
        public virtual ObjectResult<string> enazsatılanurun()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("enazsatılanurun");
        }
    
        public virtual ObjectResult<string> encokalımlımüşteri()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("encokalımlımüşteri");
        }
    
        public virtual ObjectResult<string> encoksatılankategorı()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("encoksatılankategorı");
        }
    
        public virtual ObjectResult<string> encoksatılanMarka()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("encoksatılanMarka");
        }
    
        public virtual ObjectResult<Nullable<decimal>> trendfiyat()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("trendfiyat");
        }
    
        public virtual ObjectResult<string> trendgörsel()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("trendgörsel");
        }
    }
}
